// PD3, PD4, PD5 -> GPIO_Output

while (1) 
{
  //There's another line here
  HAL_GPIO_WritePin(GPIOD, GPIO_PIN_3, SET);
  HAL_Delay(500);
  HAL_GPIO_WritePin(GPIOD, GPIO_PIN_3, RESET);

  HAL_GPIO_WritePin(GPIOD, GPIO_PIN_4, SET);
  HAL_Delay(500);
  HAL_GPIO_WritePin(GPIOD, GPIO_PIN_4, RESET);

  HAL_GPIO_WritePin(GPIOD, GPIO_PIN_5, SET);
  HAL_Delay(500);
  HAL_GPIO_WritePin(GPIOD, GPIO_PIN_5, RESET);

  HAL_GPIO_WritePin(GPIOD, GPIO_PIN_3, SET);
  HAL_GPIO_WritePin(GPIOD, GPIO_PIN_4, SET);
  HAL_GPIO_WritePin(GPIOD, GPIO_PIN_5, SET);
  HAL_Delay(1000);
  HAL_GPIO_WritePin(GPIOD, GPIO_PIN_3, RESET);
  HAL_GPIO_WritePin(GPIOD, GPIO_PIN_4, RESET);
  HAL_GPIO_WritePin(GPIOD, GPIO_PIN_5, RESET);
}
